apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: deepfakeshield
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-cache
  namespace: deepfakeshield
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
